name: 'maia-pac'
on:
  push:
    tags:
      - maia-pac-**

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: maia-httpd/maia-pac

jobs:
  publish:
    name: Publish Rust crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4      
    - name: Publish Rust crate
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
